#!/bin/bash
# 실사 모델 다운로드 헬퍼 스크립트 (일본 배경/사물 특화)

echo "🗾 일본 배경/사물 실사 모델 다운로드 가이드"
echo "================================================"
echo ""
echo "📋 현재 문제:"
echo "  - japaneseDollLikeness 모델은 애니메이션 전용입니다"
echo "  - realistic/cinematic 스타일을 선택해도 애니메이션 배경이 생성됩니다"
echo ""
echo "🎯 필요한 것:"
echo "  - 일본 거리, 건물, 풍경, 신사, 사찰 등 실사 배경 이미지"
echo "  - 전통 사물 (다다미, 쇼지문, 제등, 차 세트 등)"
echo "  - 자연 풍경 (벚꽃, 단풍, 설경, 바다, 산)"
echo "  - ❌ 얼굴/인물 불필요 (배경만 필요)"
echo ""
echo "✅ 해결 방법:"
echo "  → 실사 전용 모델을 다운로드해야 합니다"
echo ""
echo "================================================"
echo "추천 모델 (일본 배경 특화) 🏯"
echo "================================================"
echo ""
echo "1️⃣  Realistic Vision V5.1 (가장 추천!) ⭐⭐⭐⭐⭐"
echo "   📥 다운로드: https://civitai.com/models/4201/realistic-vision-v51"
echo "   📦 크기: ~2.1GB (pruned)"
echo "   🎨 특징:"
echo "      ✅ 일본 배경/풍경/사물 사진 품질 최고"
echo "      ✅ 거리, 신사, 전통 건축물, 자연 풍경 모두 뛰어남"
echo "      ✅ 키워드만 입력해도 사실적인 배경 생성"
echo "      ✅ 사람 없는 풍경 완벽"
echo "      ✅ macOS/MPS 지원 우수, 빠른 생성 속도"
echo "   📝 파일명: realisticVisionV51_v51VAE.safetensors"
echo ""
echo "2️⃣  Deliberate V2 (시네마틱 배경) ⭐⭐⭐⭐⭐"
echo "   📥 다운로드: https://civitai.com/models/4823/deliberate"
echo "   📦 크기: ~2.1GB"
echo "   🎨 특징:"
echo "      ✅ 영화 같은 분위기의 배경 (스토리텔링 최적)"
echo "      ✅ 드라마틱한 조명, 안개, 비, 계절감"
echo "      ✅ 감정 전달에 최적화된 풍경"
echo "      ✅ macOS에서도 빠른 생성"
echo "   📝 파일명: deliberate_v2.safetensors"
echo ""
echo "3️⃣  DreamShaper 8 (다목적 실사) ⭐⭐⭐⭐"
echo "   📥 다운로드: https://civitai.com/models/4384/dreamshaper"
echo "   📦 크기: ~2GB"
echo "   🎨 특징:"
echo "      ✅ 배경/사물 모두 우수, 가장 빠른 생성 속도"
echo "      ✅ 일본 현대/전통 장면 모두 표현"
echo "      ✅ 실내 사물 디테일 좋음"
echo "   📝 파일명: dreamshaper_8.safetensors"
echo ""
echo "================================================"
echo "📂 설치 방법:"
echo "================================================"
echo ""
echo "1️⃣  CivitAI에서 모델 다운로드 (무료 회원가입 필요)"
echo "   https://civitai.com/models/4201/realistic-vision-v51"
echo ""
echo "2️⃣  다운로드한 파일을 SD WebUI 모델 폴더로 이동:"
echo ""
echo "   mv ~/Downloads/realisticVisionV51_v51VAE.safetensors \\"
echo "      /Users/systemi/stable-diffusion-webui/models/Stable-diffusion/"
echo ""
echo "3️⃣  SD WebUI 재시작:"
echo ""
echo "   cd /Users/systemi/stable-diffusion-webui"
echo "   ./webui.sh --port 7861"
echo ""
echo "4️⃣  Storymaker에서 모델 사용:"
echo ""
echo "   A. SD WebUI 브라우저 열기: http://127.0.0.1:7861"
echo "   B. 상단 Checkpoint 드롭다운 클릭"
echo "   C. 'realisticVisionV51_v51VAE' 선택"
echo "   D. Storymaker에서 '이미지 스타일: realistic' 선택"
echo "   E. 이미지 생성 → 실사 일본 배경 생성 ✅"
echo ""
echo "================================================"
echo "🗾 일본 배경 프롬프트 예시:"
echo "================================================"
echo ""
echo "🏘️  전통 거리:"
echo "   Japanese traditional street, Kyoto style, old wooden buildings,"
echo "   stone pavement, lanterns, morning light, photorealistic, no people"
echo ""
echo "🏯 신사/사찰:"
echo "   Japanese shrine, torii gate, stone lanterns, autumn leaves,"
echo "   peaceful atmosphere, natural lighting, photorealistic"
echo ""
echo "🌸 자연 풍경:"
echo "   Japanese cherry blossom trees, sakura petals falling,"
echo "   spring season, photorealistic, no people"
echo ""
echo "🏠 실내 사물:"
echo "   Traditional Japanese room, tatami floor, shoji screen,"
echo "   natural light, minimalist interior, photorealistic"
echo ""
echo "================================================"
echo ""

# 현재 모델 폴더 내용 확인
echo "📂 현재 설치된 모델:"
echo ""
ls -lh /Users/systemi/stable-diffusion-webui/models/Stable-diffusion/ | grep -v "^d" | tail -n +2
echo ""
echo "================================================"
echo ""
echo "💡 팁:"
echo "  - 모델 파일은 5GB 내외로 큽니다 (저장 공간 확인)"
echo "  - 첫 로딩 시 1-2분 소요됩니다"
echo "  - macOS는 CUDA보다 느립니다 (정상)"
echo ""
echo "❓ 문제 해결:"
echo "  - CivitAI 링크 안 열림 → 무료 회원가입 필요"
echo "  - 용량 부족 → 1개만 다운로드 (Realistic Vision 추천)"
echo "  - 로딩 느림 → macOS 특성상 정상"
echo ""
